[2013-01-22 10:32:29,863: WARNING/MainProcess] celery@holly ready.
[2013-01-22 10:32:29,871: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-01-22 10:36:21,264: INFO/MainProcess] Got task from broker: slavedriver.webfetch.plos_lookup[e9eae983-9660-4fd3-ac3e-74ae377750a1]
[2013-01-22 10:36:21,287: INFO/MainProcess] Task slavedriver.webfetch.plos_lookup[e9eae983-9660-4fd3-ac3e-74ae377750a1] succeeded in 0.00449204444885s: u'delay - DOI?'
[2013-01-22 10:36:25,106: INFO/MainProcess] Got task from broker: slavedriver.webfetch.plos_lookup[3c9145fd-19ea-44a7-b429-f127227841d6]
[2013-01-22 10:36:25,159: INFO/MainProcess] Task slavedriver.webfetch.plos_lookup[3c9145fd-19ea-44a7-b429-f127227841d6] succeeded in 0.00476408004761s: u'delay - DOI?'
[2013-01-27 17:32:59,000: WARNING/MainProcess] celery@holly ready.
[2013-01-27 17:32:59,010: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-01-27 17:57:33,966: WARNING/MainProcess] celery@holly ready.
[2013-01-27 17:57:33,974: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-01-27 18:03:21,707: WARNING/MainProcess] celery@holly ready.
[2013-01-27 18:03:21,715: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-01-27 18:04:05,667: INFO/MainProcess] Got task from broker: slavedriver.workers.detect_provider[a1efdf0a-ffc3-444a-9728-ab6aed6e2d5e]
[2013-01-27 18:04:05,727: INFO/MainProcess] Got task from broker: slavedriver.workers.provider_site_plugins[2b9c5e58-c69e-47da-bdf6-73f4af4d9bdd]
[2013-01-27 18:04:05,728: INFO/MainProcess] Task slavedriver.workers.detect_provider[a1efdf0a-ffc3-444a-9728-ab6aed6e2d5e] succeeded in 0.0178081989288s: {u'canonical': u'doi:123456', u'type':...
[2013-01-27 18:04:05,761: INFO/MainProcess] Got task from broker: slavedriver.workers.provider_page_plugins[d3bc0e63-0617-461a-83d9-1a7ed839970d]
[2013-01-27 18:04:05,763: INFO/MainProcess] Task slavedriver.workers.provider_site_plugins[2b9c5e58-c69e-47da-bdf6-73f4af4d9bdd] succeeded in 0.0177299976349s: {u'canonical': u'doi:123456', u'type':...
[2013-01-27 18:04:05,771: INFO/MainProcess] Task slavedriver.workers.provider_page_plugins[d3bc0e63-0617-461a-83d9-1a7ed839970d] succeeded in 0.00615000724792s: {u'queued': True, 'licence': {'url':...
[2013-02-12 21:29:45,689: WARNING/MainProcess] celery@holly ready.
[2013-02-12 21:29:45,699: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 21:29:45,722: ERROR/MainProcess] Received unregistered task of type u'slavedriver.workers.detect_provider'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
More: http://docs.celeryq.org/en/latest/userguide/tasks.html#names

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [{u'canonical': u'doi:123456', u'type': u'doi', u'id': u'123456', u'queued': True}], u'retries': 0, u'expires': None, u'task': u'slavedriver.workers.detect_provider', u'callbacks': [{u'task': u'slavedriver.workers.provider_site_plugins', u'args': [], u'options': {u'link': [{u'task': u'slavedriver.workers.provider_page_plugins', u'args': [], u'options': {u'task_id': u'bbf1cb48-38a7-4b0d-a60e-ccadb2834048'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'b75a4264-f1b4-46f6-8c6d-864af804500e'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'196c5e2c-73c9-4725-8c68-6877c50f50ee'} (699b)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 435, in on_task_received
    strategies[name](message, body, message.ack_log_error)
KeyError: u'slavedriver.workers.detect_provider'
[2013-02-12 21:35:50,638: ERROR/MainProcess] Received unregistered task of type u'workflow.detect_provider'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
More: http://docs.celeryq.org/en/latest/userguide/tasks.html#names

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], u'retries': 0, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': [{u'task': u'workflow.provider_licence', u'args': [], u'options': {u'link': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'61f60539-0397-4d80-bd49-f65d2de3f10c'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'1b278029-07ab-4adf-b996-f2d8f45c8c02'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'cd491009-1307-47d8-ba41-4c0b0940e0b2'} (665b)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 435, in on_task_received
    strategies[name](message, body, message.ack_log_error)
KeyError: u'workflow.detect_provider'
[2013-02-12 21:39:09,890: WARNING/MainProcess] celery@holly ready.
[2013-02-12 21:39:09,898: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 21:41:10,654: WARNING/MainProcess] celery@holly ready.
[2013-02-12 21:41:10,663: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 21:43:05,288: INFO/MainProcess] Got task from broker: workflow.detect_provider[ff217b12-9c5c-4ea2-af71-2f7b6edae0a2]
[2013-02-12 21:43:05,316: ERROR/MainProcess] Task workflow.detect_provider[ff217b12-9c5c-4ea2-af71-2f7b6edae0a2] raised exception: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 407, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/richard/Code/External/IsItOpenAccess/src/workflow.py", line 259, in detect_provider
    plugin(record)
TypeError: 'NoneType' object is not callable
[2013-02-12 21:44:01,971: INFO/MainProcess] Got task from broker: workflow.detect_provider[dc01b812-02e1-42ec-a93c-f999f067e810]
[2013-02-12 21:44:02,020: ERROR/MainProcess] Task workflow.detect_provider[dc01b812-02e1-42ec-a93c-f999f067e810] raised exception: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 407, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/richard/Code/External/IsItOpenAccess/src/workflow.py", line 259, in detect_provider
    plugin(record)
TypeError: 'NoneType' object is not callable
[2013-02-12 21:44:57,972: WARNING/MainProcess] celery@holly ready.
[2013-02-12 21:44:57,980: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 21:45:54,234: INFO/MainProcess] Got task from broker: workflow.detect_provider[1ebc99d5-cbf0-47c5-b744-df1406ce57a8]
[2013-02-12 21:45:54,290: ERROR/MainProcess] Task workflow.detect_provider[1ebc99d5-cbf0-47c5-b744-df1406ce57a8] raised exception: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 407, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/richard/Code/External/IsItOpenAccess/src/workflow.py", line 259, in detect_provider
    plugin(record)
TypeError: 'NoneType' object is not callable
[2013-02-12 21:46:13,342: DEBUG/MainProcess] [Worker] Loading modules.
[2013-02-12 21:46:13,405: DEBUG/MainProcess] [Worker] Claiming components.
[2013-02-12 21:46:13,406: DEBUG/MainProcess] [Worker] Building boot step graph.
[2013-02-12 21:46:13,407: DEBUG/MainProcess] [Worker] New boot order: {ev, queues, beat, pool, mediator, autoreloader, timers, state-db, autoscaler, consumer}
[2013-02-12 21:46:13,414: DEBUG/MainProcess] Starting celery.worker.hub.Hub...
[2013-02-12 21:46:13,414: DEBUG/MainProcess] celery.worker.hub.Hub OK!
[2013-02-12 21:46:13,415: DEBUG/MainProcess] Starting celery.concurrency.processes.TaskPool...
[2013-02-12 21:46:13,434: DEBUG/MainProcess] celery.concurrency.processes.TaskPool OK!
[2013-02-12 21:46:13,435: DEBUG/MainProcess] Starting celery.worker.mediator.Mediator...
[2013-02-12 21:46:13,436: DEBUG/MainProcess] celery.worker.mediator.Mediator OK!
[2013-02-12 21:46:13,437: DEBUG/MainProcess] Starting celery.worker.consumer.Consumer...
[2013-02-12 21:46:13,438: WARNING/MainProcess] celery@holly ready.
[2013-02-12 21:46:13,439: DEBUG/MainProcess] consumer: Re-establishing connection to the broker...
[2013-02-12 21:46:13,445: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 21:46:13,449: DEBUG/MainProcess] consumer: basic.qos: prefetch_count->16
[2013-02-12 21:46:13,462: DEBUG/MainProcess] consumer: Ready to accept tasks!
[2013-02-12 21:46:18,569: INFO/MainProcess] Got task from broker: workflow.detect_provider[0b365897-4a7c-4bdf-aaf3-7f47f38097ee]
[2013-02-12 21:46:18,609: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[0b365897-4a7c-4bdf-aaf3-7f47f38097ee]
[2013-02-12 21:46:18,610: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x1f66848> (args:(u'workflow.detect_provider', u'0b365897-4a7c-4bdf-aaf3-7f47f38097ee', [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'0b365897-4a7c-4bdf-aaf3-7f47f38097ee'}) kwargs:{})
[2013-02-12 21:46:18,614: DEBUG/MainProcess] Task accepted: workflow.detect_provider[0b365897-4a7c-4bdf-aaf3-7f47f38097ee] pid:27382
[2013-02-12 21:46:18,614: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-12 21:46:18,622: ERROR/MainProcess] Task workflow.detect_provider[0b365897-4a7c-4bdf-aaf3-7f47f38097ee] raised exception: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 407, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/richard/Code/External/IsItOpenAccess/src/workflow.py", line 259, in detect_provider
    plugin(record)
TypeError: 'NoneType' object is not callable
[2013-02-12 21:59:25,756: DEBUG/MainProcess] Stopping celery.worker.consumer.Consumer...
[2013-02-12 21:59:25,757: DEBUG/MainProcess] consumer: Stopping consumers...
[2013-02-12 21:59:25,757: DEBUG/MainProcess] Stopping celery.worker.mediator.Mediator...
[2013-02-12 21:59:26,157: DEBUG/MainProcess] Stopping celery.concurrency.processes.TaskPool...
[2013-02-12 21:59:26,167: DEBUG/MainProcess] Stopping celery.worker.hub.Hub...
[2013-02-12 21:59:26,167: DEBUG/MainProcess] consumer: Closing consumer channel...
[2013-02-12 21:59:26,168: DEBUG/MainProcess] consumer: Closing broadcast channel...
[2013-02-12 21:59:26,171: DEBUG/MainProcess] consumer: Closing broker connection...
[2013-02-12 21:59:27,676: DEBUG/MainProcess] [Worker] Loading modules.
[2013-02-12 21:59:27,737: DEBUG/MainProcess] [Worker] Claiming components.
[2013-02-12 21:59:27,738: DEBUG/MainProcess] [Worker] Building boot step graph.
[2013-02-12 21:59:27,739: DEBUG/MainProcess] [Worker] New boot order: {ev, queues, beat, pool, mediator, autoreloader, timers, state-db, autoscaler, consumer}
[2013-02-12 21:59:27,745: DEBUG/MainProcess] Starting celery.worker.hub.Hub...
[2013-02-12 21:59:27,746: DEBUG/MainProcess] celery.worker.hub.Hub OK!
[2013-02-12 21:59:27,747: DEBUG/MainProcess] Starting celery.concurrency.processes.TaskPool...
[2013-02-12 21:59:27,766: DEBUG/MainProcess] celery.concurrency.processes.TaskPool OK!
[2013-02-12 21:59:27,768: DEBUG/MainProcess] Starting celery.worker.mediator.Mediator...
[2013-02-12 21:59:27,769: DEBUG/MainProcess] celery.worker.mediator.Mediator OK!
[2013-02-12 21:59:27,770: DEBUG/MainProcess] Starting celery.worker.consumer.Consumer...
[2013-02-12 21:59:27,771: WARNING/MainProcess] celery@holly ready.
[2013-02-12 21:59:27,772: DEBUG/MainProcess] consumer: Re-establishing connection to the broker...
[2013-02-12 21:59:27,778: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 21:59:27,782: DEBUG/MainProcess] consumer: basic.qos: prefetch_count->16
[2013-02-12 21:59:27,795: DEBUG/MainProcess] consumer: Ready to accept tasks!
[2013-02-12 21:59:37,233: INFO/MainProcess] Got task from broker: workflow.detect_provider[87994af6-dd4f-47bd-8b8e-5d90c50dd056]
[2013-02-12 21:59:37,243: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[87994af6-dd4f-47bd-8b8e-5d90c50dd056]
[2013-02-12 21:59:37,244: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x2665848> (args:(u'workflow.detect_provider', u'87994af6-dd4f-47bd-8b8e-5d90c50dd056', [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'87994af6-dd4f-47bd-8b8e-5d90c50dd056'}) kwargs:{})
[2013-02-12 21:59:37,247: DEBUG/MainProcess] Task accepted: workflow.detect_provider[87994af6-dd4f-47bd-8b8e-5d90c50dd056] pid:27492
[2013-02-12 21:59:37,246: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-12 21:59:37,248: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-12 21:59:37,249: DEBUG/MainProcess] import error loading provider_range_lookup from iioa.plugins.doi - path may not be accessible or available in this context
[2013-02-12 21:59:37,249: DEBUG/MainProcess] unable to load plugin provider_range_lookup from plugins.doi
[2013-02-12 21:59:37,249: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-12 21:59:37,256: ERROR/MainProcess] Task workflow.detect_provider[87994af6-dd4f-47bd-8b8e-5d90c50dd056] raised exception: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 407, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/richard/Code/External/IsItOpenAccess/src/workflow.py", line 259, in detect_provider
    plugin(record)
TypeError: 'NoneType' object is not callable
[2013-02-12 22:15:07,131: DEBUG/MainProcess] Stopping celery.worker.consumer.Consumer...
[2013-02-12 22:15:07,131: DEBUG/MainProcess] consumer: Stopping consumers...
[2013-02-12 22:15:07,132: DEBUG/MainProcess] Stopping celery.worker.mediator.Mediator...
[2013-02-12 22:15:07,911: DEBUG/MainProcess] Stopping celery.concurrency.processes.TaskPool...
[2013-02-12 22:15:07,918: DEBUG/MainProcess] Stopping celery.worker.hub.Hub...
[2013-02-12 22:15:07,919: DEBUG/MainProcess] consumer: Closing consumer channel...
[2013-02-12 22:15:07,919: DEBUG/MainProcess] consumer: Closing broadcast channel...
[2013-02-12 22:15:07,922: DEBUG/MainProcess] consumer: Closing broker connection...
[2013-02-12 22:17:14,056: DEBUG/MainProcess] [Worker] Loading modules.
[2013-02-12 22:17:14,120: DEBUG/MainProcess] [Worker] Claiming components.
[2013-02-12 22:17:14,120: DEBUG/MainProcess] [Worker] Building boot step graph.
[2013-02-12 22:17:14,122: DEBUG/MainProcess] [Worker] New boot order: {ev, queues, beat, pool, mediator, autoreloader, timers, state-db, autoscaler, consumer}
[2013-02-12 22:17:14,128: DEBUG/MainProcess] Starting celery.worker.hub.Hub...
[2013-02-12 22:17:14,129: DEBUG/MainProcess] celery.worker.hub.Hub OK!
[2013-02-12 22:17:14,129: DEBUG/MainProcess] Starting celery.concurrency.processes.TaskPool...
[2013-02-12 22:17:14,147: DEBUG/MainProcess] celery.concurrency.processes.TaskPool OK!
[2013-02-12 22:17:14,149: DEBUG/MainProcess] Starting celery.worker.mediator.Mediator...
[2013-02-12 22:17:14,151: DEBUG/MainProcess] celery.worker.mediator.Mediator OK!
[2013-02-12 22:17:14,152: DEBUG/MainProcess] Starting celery.worker.consumer.Consumer...
[2013-02-12 22:17:14,153: WARNING/MainProcess] celery@holly ready.
[2013-02-12 22:17:14,154: DEBUG/MainProcess] consumer: Re-establishing connection to the broker...
[2013-02-12 22:17:14,161: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 22:17:14,165: DEBUG/MainProcess] consumer: basic.qos: prefetch_count->16
[2013-02-12 22:17:14,182: DEBUG/MainProcess] consumer: Ready to accept tasks!
[2013-02-12 22:18:16,020: INFO/MainProcess] Got task from broker: workflow.detect_provider[ed5f8834-a1e6-47c5-b7fd-0015e65bc2cb]
[2013-02-12 22:18:16,064: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[ed5f8834-a1e6-47c5-b7fd-0015e65bc2cb]
[2013-02-12 22:18:16,065: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x1f21578> (args:(u'workflow.detect_provider', u'ed5f8834-a1e6-47c5-b7fd-0015e65bc2cb', [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'ed5f8834-a1e6-47c5-b7fd-0015e65bc2cb'}) kwargs:{})
[2013-02-12 22:18:16,067: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-12 22:18:16,068: DEBUG/MainProcess] Task accepted: workflow.detect_provider[ed5f8834-a1e6-47c5-b7fd-0015e65bc2cb] pid:27635
[2013-02-12 22:18:16,069: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-12 22:18:16,071: DEBUG/MainProcess] import error loading provider_range_lookup from isitopenaccess.plugins.doi - path may not be accessible or available in this context
[2013-02-12 22:18:16,071: DEBUG/MainProcess] unable to load plugin provider_range_lookup from plugins.doi
[2013-02-12 22:18:16,072: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-12 22:18:16,081: ERROR/MainProcess] Task workflow.detect_provider[ed5f8834-a1e6-47c5-b7fd-0015e65bc2cb] raised exception: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 407, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/richard/Code/External/IsItOpenAccess/src/workflow.py", line 259, in detect_provider
    plugin(record)
TypeError: 'NoneType' object is not callable
[2013-02-12 22:18:22,217: ERROR/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 393, in start
    self.consume_messages()
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 464, in consume_messages
    update_readers(on_poll_start())
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 745, in on_poll_start
    cycle.on_poll_start()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 248, in on_poll_start
    self._register_BRPOP(channel)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 231, in _register_BRPOP
    self._register(*ident)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 216, in _register
    client.connection.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 231, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting localhost:6379. Connection refused.
[2013-02-12 22:18:22,222: DEBUG/MainProcess] consumer: Re-establishing connection to the broker...
[2013-02-12 22:18:22,223: DEBUG/MainProcess] consumer: Heart: Going into cardiac arrest...
[2013-02-12 22:18:22,223: DEBUG/MainProcess] consumer: Cancelling task consumer...
[2013-02-12 22:18:22,223: DEBUG/MainProcess] consumer: Shutting down event dispatcher...
[2013-02-12 22:18:22,224: DEBUG/MainProcess] consumer: Cancelling broadcast consumer...
[2013-02-12 22:18:22,224: DEBUG/MainProcess] consumer: Closing consumer channel...
[2013-02-12 22:18:22,225: DEBUG/MainProcess] consumer: Closing broadcast channel...
[2013-02-12 22:18:22,226: DEBUG/MainProcess] consumer: Closing broker connection...
[2013-02-12 22:18:22,230: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting localhost:6379. Connection refused..
Trying again in 2.00 seconds...

[2013-02-12 22:18:24,234: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting localhost:6379. Connection refused..
Trying again in 4.00 seconds...

[2013-02-12 22:18:28,242: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 22:18:28,245: DEBUG/MainProcess] consumer: basic.qos: prefetch_count->16
[2013-02-12 22:18:28,253: DEBUG/MainProcess] consumer: Ready to accept tasks!
[2013-02-12 22:23:45,790: DEBUG/MainProcess] [Worker] Loading modules.
[2013-02-12 22:23:45,851: DEBUG/MainProcess] [Worker] Claiming components.
[2013-02-12 22:23:45,852: DEBUG/MainProcess] [Worker] Building boot step graph.
[2013-02-12 22:23:45,853: DEBUG/MainProcess] [Worker] New boot order: {ev, queues, beat, pool, mediator, autoreloader, timers, state-db, autoscaler, consumer}
[2013-02-12 22:23:45,860: DEBUG/MainProcess] Starting celery.worker.hub.Hub...
[2013-02-12 22:23:45,861: DEBUG/MainProcess] celery.worker.hub.Hub OK!
[2013-02-12 22:23:45,862: DEBUG/MainProcess] Starting celery.concurrency.processes.TaskPool...
[2013-02-12 22:23:45,881: DEBUG/MainProcess] celery.concurrency.processes.TaskPool OK!
[2013-02-12 22:23:45,883: DEBUG/MainProcess] Starting celery.worker.mediator.Mediator...
[2013-02-12 22:23:45,884: DEBUG/MainProcess] celery.worker.mediator.Mediator OK!
[2013-02-12 22:23:45,885: DEBUG/MainProcess] Starting celery.worker.consumer.Consumer...
[2013-02-12 22:23:45,886: WARNING/MainProcess] celery@holly ready.
[2013-02-12 22:23:45,886: DEBUG/MainProcess] consumer: Re-establishing connection to the broker...
[2013-02-12 22:23:45,894: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 22:23:45,897: DEBUG/MainProcess] consumer: basic.qos: prefetch_count->16
[2013-02-12 22:23:45,911: DEBUG/MainProcess] consumer: Ready to accept tasks!
[2013-02-12 22:23:55,394: INFO/MainProcess] Got task from broker: workflow.detect_provider[a6c6a235-295b-4341-afd6-64632651498a]
[2013-02-12 22:23:55,414: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[a6c6a235-295b-4341-afd6-64632651498a]
[2013-02-12 22:23:55,414: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x268f5f0> (args:(u'workflow.detect_provider', u'a6c6a235-295b-4341-afd6-64632651498a', [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'a6c6a235-295b-4341-afd6-64632651498a'}) kwargs:{})
[2013-02-12 22:23:55,417: DEBUG/MainProcess] Task accepted: workflow.detect_provider[a6c6a235-295b-4341-afd6-64632651498a] pid:27826
[2013-02-12 22:23:55,417: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-12 22:23:55,419: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-12 22:23:55,423: DEBUG/MainProcess] import error loading provider_range_lookup from isitopenaccess.plugins.doi - path may not be accessible or available in this context
[2013-02-12 22:23:55,423: DEBUG/MainProcess] unable to load plugin provider_range_lookup from plugins.doi
[2013-02-12 22:23:55,424: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-12 22:23:55,434: ERROR/MainProcess] Task workflow.detect_provider[a6c6a235-295b-4341-afd6-64632651498a] raised exception: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 407, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/richard/Code/External/IsItOpenAccess/isitopenaccess/workflow.py", line 259, in detect_provider
    plugin(record)
TypeError: 'NoneType' object is not callable
[2013-02-12 22:37:04,604: DEBUG/MainProcess] Stopping celery.worker.consumer.Consumer...
[2013-02-12 22:37:04,605: DEBUG/MainProcess] consumer: Stopping consumers...
[2013-02-12 22:37:04,605: DEBUG/MainProcess] Stopping celery.worker.mediator.Mediator...
[2013-02-12 22:37:04,986: DEBUG/MainProcess] Stopping celery.concurrency.processes.TaskPool...
[2013-02-12 22:37:04,992: DEBUG/MainProcess] Stopping celery.worker.hub.Hub...
[2013-02-12 22:37:04,993: DEBUG/MainProcess] consumer: Closing consumer channel...
[2013-02-12 22:37:04,994: DEBUG/MainProcess] consumer: Closing broadcast channel...
[2013-02-12 22:37:04,996: DEBUG/MainProcess] consumer: Closing broker connection...
[2013-02-12 22:37:08,678: DEBUG/MainProcess] [Worker] Loading modules.
[2013-02-12 22:37:08,738: DEBUG/MainProcess] [Worker] Claiming components.
[2013-02-12 22:37:08,739: DEBUG/MainProcess] [Worker] Building boot step graph.
[2013-02-12 22:37:08,741: DEBUG/MainProcess] [Worker] New boot order: {ev, queues, beat, pool, mediator, autoreloader, timers, state-db, autoscaler, consumer}
[2013-02-12 22:37:08,747: DEBUG/MainProcess] Starting celery.worker.hub.Hub...
[2013-02-12 22:37:08,748: DEBUG/MainProcess] celery.worker.hub.Hub OK!
[2013-02-12 22:37:08,748: DEBUG/MainProcess] Starting celery.concurrency.processes.TaskPool...
[2013-02-12 22:37:08,766: DEBUG/MainProcess] celery.concurrency.processes.TaskPool OK!
[2013-02-12 22:37:08,768: DEBUG/MainProcess] Starting celery.worker.mediator.Mediator...
[2013-02-12 22:37:08,769: DEBUG/MainProcess] celery.worker.mediator.Mediator OK!
[2013-02-12 22:37:08,769: DEBUG/MainProcess] Starting celery.worker.consumer.Consumer...
[2013-02-12 22:37:08,770: WARNING/MainProcess] celery@holly ready.
[2013-02-12 22:37:08,771: DEBUG/MainProcess] consumer: Re-establishing connection to the broker...
[2013-02-12 22:37:08,778: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-12 22:37:08,781: DEBUG/MainProcess] consumer: basic.qos: prefetch_count->16
[2013-02-12 22:37:08,795: DEBUG/MainProcess] consumer: Ready to accept tasks!
[2013-02-12 22:37:24,545: INFO/MainProcess] Got task from broker: workflow.detect_provider[61e031fb-d167-416d-94fd-7ce3a8a00054]
[2013-02-12 22:37:24,551: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[61e031fb-d167-416d-94fd-7ce3a8a00054]
[2013-02-12 22:37:24,553: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x19c85f0> (args:(u'workflow.detect_provider', u'61e031fb-d167-416d-94fd-7ce3a8a00054', [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.1', u'canonical': u'doi:10.1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'61e031fb-d167-416d-94fd-7ce3a8a00054'}) kwargs:{})
[2013-02-12 22:37:24,555: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-12 22:37:24,556: DEBUG/MainProcess] Task accepted: workflow.detect_provider[61e031fb-d167-416d-94fd-7ce3a8a00054] pid:27888
[2013-02-12 22:37:24,557: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-12 22:37:24,561: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_range_lookup at 0x1dce7d0>
[2013-02-12 22:37:24,562: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-12 22:37:24,562: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_dereference
[2013-02-12 22:37:24,563: DEBUG/MainProcess] import error loading provider_dereference from plugins.doi - path may not be accessible or available in this context
[2013-02-12 22:37:24,563: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_dereference at 0x1dce848>
[2013-02-12 22:37:24,564: DEBUG/MainProcess] applying plugin plugins.doi.provider_dereference
[2013-02-12 22:37:24,568: INFO/MainProcess] Task workflow.detect_provider[61e031fb-d167-416d-94fd-7ce3a8a00054] succeeded in 0.0140500068665s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,043: DEBUG/MainProcess] [Worker] Loading modules.
[2013-02-20 00:18:41,105: DEBUG/MainProcess] [Worker] Claiming components.
[2013-02-20 00:18:41,105: DEBUG/MainProcess] [Worker] Building boot step graph.
[2013-02-20 00:18:41,107: DEBUG/MainProcess] [Worker] New boot order: {ev, queues, beat, pool, mediator, autoreloader, timers, state-db, autoscaler, consumer}
[2013-02-20 00:18:41,114: DEBUG/MainProcess] Starting celery.worker.hub.Hub...
[2013-02-20 00:18:41,114: DEBUG/MainProcess] celery.worker.hub.Hub OK!
[2013-02-20 00:18:41,115: DEBUG/MainProcess] Starting celery.concurrency.processes.TaskPool...
[2013-02-20 00:18:41,134: DEBUG/MainProcess] celery.concurrency.processes.TaskPool OK!
[2013-02-20 00:18:41,136: DEBUG/MainProcess] Starting celery.worker.mediator.Mediator...
[2013-02-20 00:18:41,138: DEBUG/MainProcess] celery.worker.mediator.Mediator OK!
[2013-02-20 00:18:41,138: DEBUG/MainProcess] Starting celery.worker.consumer.Consumer...
[2013-02-20 00:18:41,139: WARNING/MainProcess] celery@holly ready.
[2013-02-20 00:18:41,139: DEBUG/MainProcess] consumer: Re-establishing connection to the broker...
[2013-02-20 00:18:41,146: INFO/MainProcess] consumer: Connected to redis://localhost:6379//.
[2013-02-20 00:18:41,150: DEBUG/MainProcess] consumer: basic.qos: prefetch_count->16
[2013-02-20 00:18:41,169: DEBUG/MainProcess] consumer: Ready to accept tasks!
[2013-02-20 00:18:41,172: INFO/MainProcess] Got task from broker: workflow.detect_provider[dad7eaf0-7f53-4bea-b99e-38147f9d080c]
[2013-02-20 00:18:41,175: INFO/MainProcess] Got task from broker: workflow.detect_provider[4eee9812-4d46-4535-900d-2434129c6ea5]
[2013-02-20 00:18:41,177: INFO/MainProcess] Got task from broker: workflow.detect_provider[1f2b5f7a-8f7e-4176-b76f-f10278cfcd1a]
[2013-02-20 00:18:41,178: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[dad7eaf0-7f53-4bea-b99e-38147f9d080c]
[2013-02-20 00:18:41,179: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.detect_provider', u'dad7eaf0-7f53-4bea-b99e-38147f9d080c', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': [{u'task': u'workflow.provider_licence', u'args': [], u'options': {u'link': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'0f4806e3-8044-4850-b1d2-711d201013a2'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'137cbcf4-a07d-453c-b24e-98d2a7cfc336'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'dad7eaf0-7f53-4bea-b99e-38147f9d080c'}) kwargs:{})
[2013-02-20 00:18:41,182: INFO/MainProcess] Got task from broker: workflow.detect_provider[22205d25-f2d2-4a8a-a0b2-9da605022334]
[2013-02-20 00:18:41,183: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[4eee9812-4d46-4535-900d-2434129c6ea5]
[2013-02-20 00:18:41,183: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-20 00:18:41,184: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.detect_provider', u'4eee9812-4d46-4535-900d-2434129c6ea5', [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': [{u'task': u'workflow.provider_licence', u'args': [], u'options': {u'link': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'aceb01b0-d479-4e5f-9186-d6717215cfa0'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'5d6fb341-3ec8-4af1-9d54-a70340e82722'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'4eee9812-4d46-4535-900d-2434129c6ea5'}) kwargs:{})
[2013-02-20 00:18:41,185: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,187: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-20 00:18:41,188: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[1f2b5f7a-8f7e-4176-b76f-f10278cfcd1a]
[2013-02-20 00:18:41,189: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,189: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.detect_provider', u'1f2b5f7a-8f7e-4176-b76f-f10278cfcd1a', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': [{u'task': u'workflow.provider_licence', u'args': [], u'options': {u'link': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'6e7a0113-80ae-41ac-8496-4f1f2ea20a6b'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'4e4a8b5c-f33c-4104-a3d7-b0c873474430'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'1f2b5f7a-8f7e-4176-b76f-f10278cfcd1a'}) kwargs:{})
[2013-02-20 00:18:41,191: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_range_lookup at 0x1494cf8>
[2013-02-20 00:18:41,191: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-20 00:18:41,192: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_dereference
[2013-02-20 00:18:41,192: DEBUG/MainProcess] import error loading provider_dereference from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,193: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_dereference at 0x1494d70>
[2013-02-20 00:18:41,193: DEBUG/MainProcess] applying plugin plugins.doi.provider_dereference
[2013-02-20 00:18:41,190: DEBUG/MainProcess] Task accepted: workflow.detect_provider[dad7eaf0-7f53-4bea-b99e-38147f9d080c] pid:30157
[2013-02-20 00:18:41,193: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-20 00:18:41,195: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,196: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_range_lookup at 0x1494cf8>
[2013-02-20 00:18:41,196: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-20 00:18:41,197: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_dereference
[2013-02-20 00:18:41,199: DEBUG/MainProcess] import error loading provider_dereference from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,200: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_dereference at 0x1494d70>
[2013-02-20 00:18:41,200: DEBUG/MainProcess] applying plugin plugins.doi.provider_dereference
[2013-02-20 00:18:41,202: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_range_lookup at 0x1494cf8>
[2013-02-20 00:18:41,198: DEBUG/MainProcess] Task accepted: workflow.detect_provider[4eee9812-4d46-4535-900d-2434129c6ea5] pid:30160
[2013-02-20 00:18:41,202: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-20 00:18:41,202: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_dereference
[2013-02-20 00:18:41,199: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[22205d25-f2d2-4a8a-a0b2-9da605022334]
[2013-02-20 00:18:41,203: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.detect_provider', u'22205d25-f2d2-4a8a-a0b2-9da605022334', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': [{u'task': u'workflow.provider_licence', u'args': [], u'options': {u'link': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'5078683e-45df-4a4e-b13b-235f5c7f3bd1'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'b9a62e6d-caad-40dc-8712-89981f92e33d'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'22205d25-f2d2-4a8a-a0b2-9da605022334'}) kwargs:{})
[2013-02-20 00:18:41,204: DEBUG/MainProcess] import error loading provider_dereference from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,204: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_dereference at 0x1494d70>
[2013-02-20 00:18:41,204: DEBUG/MainProcess] applying plugin plugins.doi.provider_dereference
[2013-02-20 00:18:41,206: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-20 00:18:41,208: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,210: DEBUG/MainProcess] Task accepted: workflow.detect_provider[1f2b5f7a-8f7e-4176-b76f-f10278cfcd1a] pid:30158
[2013-02-20 00:18:41,212: DEBUG/MainProcess] Task accepted: workflow.detect_provider[22205d25-f2d2-4a8a-a0b2-9da605022334] pid:30159
[2013-02-20 00:18:41,213: INFO/MainProcess] Got task from broker: workflow.detect_provider[8147a2ea-f5c3-4136-9499-bd60ceda65b9]
[2013-02-20 00:18:41,214: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_range_lookup at 0x1494cf8>
[2013-02-20 00:18:41,214: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-20 00:18:41,215: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_dereference
[2013-02-20 00:18:41,217: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[8147a2ea-f5c3-4136-9499-bd60ceda65b9]
[2013-02-20 00:18:41,217: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.detect_provider', u'8147a2ea-f5c3-4136-9499-bd60ceda65b9', [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': [{u'task': u'workflow.provider_licence', u'args': [], u'options': {u'link': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'baef5929-6454-432e-8b84-90b693427f24'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'3d82f09d-ac13-4666-8ebe-3eb0240d3257'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'8147a2ea-f5c3-4136-9499-bd60ceda65b9'}) kwargs:{})
[2013-02-20 00:18:41,216: DEBUG/MainProcess] import error loading provider_dereference from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,219: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_dereference at 0x1494d70>
[2013-02-20 00:18:41,219: DEBUG/MainProcess] applying plugin plugins.doi.provider_dereference
[2013-02-20 00:18:41,222: INFO/MainProcess] Starting new HTTP connection (1): dx.doi.org
[2013-02-20 00:18:41,222: INFO/MainProcess] Got task from broker: workflow.detect_provider[19b6f336-2b2e-4aa1-a7ba-8d62083bc6d8]
[2013-02-20 00:18:41,226: INFO/MainProcess] Got task from broker: workflow.detect_provider[b5528098-378d-4af7-85bb-20d08203efa1]
[2013-02-20 00:18:41,227: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[19b6f336-2b2e-4aa1-a7ba-8d62083bc6d8]
[2013-02-20 00:18:41,228: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.detect_provider', u'19b6f336-2b2e-4aa1-a7ba-8d62083bc6d8', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': [{u'task': u'workflow.provider_licence', u'args': [], u'options': {u'link': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'75a2e33d-b5fd-4209-a979-0b44a5bb47ef'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'ad92d569-929c-49cd-a6ba-18f48a01bdbc'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'19b6f336-2b2e-4aa1-a7ba-8d62083bc6d8'}) kwargs:{})
[2013-02-20 00:18:41,229: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[b5528098-378d-4af7-85bb-20d08203efa1]
[2013-02-20 00:18:41,230: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.detect_provider', u'b5528098-378d-4af7-85bb-20d08203efa1', [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': [{u'task': u'workflow.provider_licence', u'args': [], u'options': {u'link': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'acf07e2e-1c57-49f6-aba9-36ee70a4a8ee'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'5214205e-b9d1-4e49-a097-2ad58fef2755'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'b5528098-378d-4af7-85bb-20d08203efa1'}) kwargs:{})
[2013-02-20 00:18:41,231: INFO/MainProcess] Starting new HTTP connection (1): dx.doi.org
[2013-02-20 00:18:41,237: INFO/MainProcess] Starting new HTTP connection (1): dx.doi.org
[2013-02-20 00:18:41,241: INFO/MainProcess] Starting new HTTP connection (1): dx.doi.org
[2013-02-20 00:18:41,496: DEBUG/MainProcess] "GET /10.stale/1 HTTP/1.1" 404 2532
[2013-02-20 00:18:41,509: INFO/MainProcess] Got task from broker: workflow.provider_licence[b9a62e6d-caad-40dc-8712-89981f92e33d]
[2013-02-20 00:18:41,510: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-20 00:18:41,511: INFO/MainProcess] Task workflow.detect_provider[22205d25-f2d2-4a8a-a0b2-9da605022334] succeeded in 0.305140972137s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,511: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,511: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_range_lookup at 0x1494cf8>
[2013-02-20 00:18:41,511: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-20 00:18:41,512: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_dereference
[2013-02-20 00:18:41,512: DEBUG/MainProcess] Task accepted: workflow.detect_provider[8147a2ea-f5c3-4136-9499-bd60ceda65b9] pid:30159
[2013-02-20 00:18:41,512: DEBUG/MainProcess] import error loading provider_dereference from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,513: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_dereference at 0x1494d70>
[2013-02-20 00:18:41,513: DEBUG/MainProcess] applying plugin plugins.doi.provider_dereference
[2013-02-20 00:18:41,515: INFO/MainProcess] Starting new HTTP connection (1): dx.doi.org
[2013-02-20 00:18:41,547: DEBUG/MainProcess] Mediator: Running callback for task: workflow.provider_licence[b9a62e6d-caad-40dc-8712-89981f92e33d]
[2013-02-20 00:18:41,547: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.provider_licence', u'b9a62e6d-caad-40dc-8712-89981f92e33d', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.provider_licence', u'callbacks': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'5078683e-45df-4a4e-b13b-235f5c7f3bd1'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'b9a62e6d-caad-40dc-8712-89981f92e33d'}) kwargs:{})
[2013-02-20 00:18:41,556: DEBUG/MainProcess] "GET /10.stale/1 HTTP/1.1" 404 2532
[2013-02-20 00:18:41,570: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-20 00:18:41,570: INFO/MainProcess] Got task from broker: workflow.provider_licence[4e4a8b5c-f33c-4104-a3d7-b0c873474430]
[2013-02-20 00:18:41,571: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,572: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_range_lookup at 0x1494cf8>
[2013-02-20 00:18:41,572: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-20 00:18:41,572: INFO/MainProcess] Task workflow.detect_provider[1f2b5f7a-8f7e-4176-b76f-f10278cfcd1a] succeeded in 0.380363941193s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,572: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_dereference
[2013-02-20 00:18:41,573: DEBUG/MainProcess] import error loading provider_dereference from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,573: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_dereference at 0x1494d70>
[2013-02-20 00:18:41,574: DEBUG/MainProcess] applying plugin plugins.doi.provider_dereference
[2013-02-20 00:18:41,574: DEBUG/MainProcess] Task accepted: workflow.detect_provider[19b6f336-2b2e-4aa1-a7ba-8d62083bc6d8] pid:30158
[2013-02-20 00:18:41,576: DEBUG/MainProcess] "GET /10.stale/1 HTTP/1.1" 404 2532
[2013-02-20 00:18:41,576: INFO/MainProcess] Starting new HTTP connection (1): dx.doi.org
[2013-02-20 00:18:41,580: DEBUG/MainProcess] Mediator: Running callback for task: workflow.provider_licence[4e4a8b5c-f33c-4104-a3d7-b0c873474430]
[2013-02-20 00:18:41,581: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.provider_licence', u'4e4a8b5c-f33c-4104-a3d7-b0c873474430', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.provider_licence', u'callbacks': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'6e7a0113-80ae-41ac-8496-4f1f2ea20a6b'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'4e4a8b5c-f33c-4104-a3d7-b0c873474430'}) kwargs:{})
[2013-02-20 00:18:41,592: INFO/MainProcess] Got task from broker: workflow.provider_licence[137cbcf4-a07d-453c-b24e-98d2a7cfc336]
[2013-02-20 00:18:41,592: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-20 00:18:41,593: INFO/MainProcess] Task workflow.detect_provider[dad7eaf0-7f53-4bea-b99e-38147f9d080c] succeeded in 0.411296844482s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,593: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,593: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_range_lookup at 0x1494cf8>
[2013-02-20 00:18:41,594: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-20 00:18:41,594: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_dereference
[2013-02-20 00:18:41,594: DEBUG/MainProcess] Task accepted: workflow.detect_provider[b5528098-378d-4af7-85bb-20d08203efa1] pid:30157
[2013-02-20 00:18:41,595: DEBUG/MainProcess] import error loading provider_dereference from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:18:41,595: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_dereference at 0x1494d70>
[2013-02-20 00:18:41,595: DEBUG/MainProcess] applying plugin plugins.doi.provider_dereference
[2013-02-20 00:18:41,597: INFO/MainProcess] Starting new HTTP connection (1): dx.doi.org
[2013-02-20 00:18:41,598: DEBUG/MainProcess] Mediator: Running callback for task: workflow.provider_licence[137cbcf4-a07d-453c-b24e-98d2a7cfc336]
[2013-02-20 00:18:41,599: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.provider_licence', u'137cbcf4-a07d-453c-b24e-98d2a7cfc336', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.provider_licence', u'callbacks': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'0f4806e3-8044-4850-b1d2-711d201013a2'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'137cbcf4-a07d-453c-b24e-98d2a7cfc336'}) kwargs:{})
[2013-02-20 00:18:41,675: DEBUG/MainProcess] "GET /10.archived/1 HTTP/1.1" 404 2544
[2013-02-20 00:18:41,687: INFO/MainProcess] Got task from broker: workflow.provider_licence[5d6fb341-3ec8-4af1-9d54-a70340e82722]
[2013-02-20 00:18:41,688: INFO/MainProcess] Task workflow.detect_provider[4eee9812-4d46-4535-900d-2434129c6ea5] succeeded in 0.501723051071s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,690: DEBUG/MainProcess] Task accepted: workflow.provider_licence[b9a62e6d-caad-40dc-8712-89981f92e33d] pid:30160
[2013-02-20 00:18:41,693: INFO/MainProcess] Got task from broker: workflow.store_results[5078683e-45df-4a4e-b13b-235f5c7f3bd1]
[2013-02-20 00:18:41,694: INFO/MainProcess] Task workflow.provider_licence[b9a62e6d-caad-40dc-8712-89981f92e33d] succeeded in 0.00653481483459s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,695: DEBUG/MainProcess] Task accepted: workflow.provider_licence[4e4a8b5c-f33c-4104-a3d7-b0c873474430] pid:30160
[2013-02-20 00:18:41,698: INFO/MainProcess] Got task from broker: workflow.store_results[6e7a0113-80ae-41ac-8496-4f1f2ea20a6b]
[2013-02-20 00:18:41,699: INFO/MainProcess] Task workflow.provider_licence[4e4a8b5c-f33c-4104-a3d7-b0c873474430] succeeded in 0.00588989257812s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,701: DEBUG/MainProcess] Task accepted: workflow.provider_licence[137cbcf4-a07d-453c-b24e-98d2a7cfc336] pid:30160
[2013-02-20 00:18:41,703: INFO/MainProcess] Task workflow.provider_licence[137cbcf4-a07d-453c-b24e-98d2a7cfc336] succeeded in 0.00482892990112s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,703: INFO/MainProcess] Got task from broker: workflow.store_results[0f4806e3-8044-4850-b1d2-711d201013a2]
[2013-02-20 00:18:41,714: DEBUG/MainProcess] Mediator: Running callback for task: workflow.store_results[5078683e-45df-4a4e-b13b-235f5c7f3bd1]
[2013-02-20 00:18:41,715: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.store_results', u'5078683e-45df-4a4e-b13b-235f5c7f3bd1', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.store_results', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'5078683e-45df-4a4e-b13b-235f5c7f3bd1'}) kwargs:{})
[2013-02-20 00:18:41,715: DEBUG/MainProcess] Mediator: Running callback for task: workflow.provider_licence[5d6fb341-3ec8-4af1-9d54-a70340e82722]
[2013-02-20 00:18:41,716: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.provider_licence', u'5d6fb341-3ec8-4af1-9d54-a70340e82722', [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.provider_licence', u'callbacks': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'aceb01b0-d479-4e5f-9186-d6717215cfa0'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'5d6fb341-3ec8-4af1-9d54-a70340e82722'}) kwargs:{})
[2013-02-20 00:18:41,718: DEBUG/MainProcess] Mediator: Running callback for task: workflow.store_results[6e7a0113-80ae-41ac-8496-4f1f2ea20a6b]
[2013-02-20 00:18:41,719: DEBUG/MainProcess] Task accepted: workflow.store_results[5078683e-45df-4a4e-b13b-235f5c7f3bd1] pid:30160
[2013-02-20 00:18:41,719: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.store_results', u'6e7a0113-80ae-41ac-8496-4f1f2ea20a6b', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.store_results', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'6e7a0113-80ae-41ac-8496-4f1f2ea20a6b'}) kwargs:{})
[2013-02-20 00:18:41,721: INFO/MainProcess] Task workflow.store_results[5078683e-45df-4a4e-b13b-235f5c7f3bd1] succeeded in 0.00524497032166s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,721: DEBUG/MainProcess] Mediator: Running callback for task: workflow.store_results[0f4806e3-8044-4850-b1d2-711d201013a2]
[2013-02-20 00:18:41,723: DEBUG/MainProcess] Task accepted: workflow.provider_licence[5d6fb341-3ec8-4af1-9d54-a70340e82722] pid:30160
[2013-02-20 00:18:41,723: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.store_results', u'0f4806e3-8044-4850-b1d2-711d201013a2', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.store_results', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'0f4806e3-8044-4850-b1d2-711d201013a2'}) kwargs:{})
[2013-02-20 00:18:41,724: INFO/MainProcess] Task workflow.provider_licence[5d6fb341-3ec8-4af1-9d54-a70340e82722] succeeded in 0.0066089630127s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,726: DEBUG/MainProcess] Task accepted: workflow.store_results[6e7a0113-80ae-41ac-8496-4f1f2ea20a6b] pid:30160
[2013-02-20 00:18:41,726: INFO/MainProcess] Task workflow.store_results[6e7a0113-80ae-41ac-8496-4f1f2ea20a6b] succeeded in 0.0055091381073s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,727: DEBUG/MainProcess] Task accepted: workflow.store_results[0f4806e3-8044-4850-b1d2-711d201013a2] pid:30160
[2013-02-20 00:18:41,728: INFO/MainProcess] Task workflow.store_results[0f4806e3-8044-4850-b1d2-711d201013a2] succeeded in 0.00323605537415s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,730: INFO/MainProcess] Got task from broker: workflow.store_results[aceb01b0-d479-4e5f-9186-d6717215cfa0]
[2013-02-20 00:18:41,733: DEBUG/MainProcess] Mediator: Running callback for task: workflow.store_results[aceb01b0-d479-4e5f-9186-d6717215cfa0]
[2013-02-20 00:18:41,733: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.store_results', u'aceb01b0-d479-4e5f-9186-d6717215cfa0', [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.store_results', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'aceb01b0-d479-4e5f-9186-d6717215cfa0'}) kwargs:{})
[2013-02-20 00:18:41,735: DEBUG/MainProcess] Task accepted: workflow.store_results[aceb01b0-d479-4e5f-9186-d6717215cfa0] pid:30160
[2013-02-20 00:18:41,736: INFO/MainProcess] Task workflow.store_results[aceb01b0-d479-4e5f-9186-d6717215cfa0] succeeded in 0.00162982940674s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,779: DEBUG/MainProcess] "GET /10.archived/1 HTTP/1.1" 200 2488
[2013-02-20 00:18:41,785: INFO/MainProcess] Got task from broker: workflow.provider_licence[3d82f09d-ac13-4666-8ebe-3eb0240d3257]
[2013-02-20 00:18:41,786: INFO/MainProcess] Task workflow.detect_provider[8147a2ea-f5c3-4136-9499-bd60ceda65b9] succeeded in 0.276226043701s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,799: DEBUG/MainProcess] Mediator: Running callback for task: workflow.provider_licence[3d82f09d-ac13-4666-8ebe-3eb0240d3257]
[2013-02-20 00:18:41,800: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.provider_licence', u'3d82f09d-ac13-4666-8ebe-3eb0240d3257', [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.provider_licence', u'callbacks': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'baef5929-6454-432e-8b84-90b693427f24'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'3d82f09d-ac13-4666-8ebe-3eb0240d3257'}) kwargs:{})
[2013-02-20 00:18:41,802: DEBUG/MainProcess] Task accepted: workflow.provider_licence[3d82f09d-ac13-4666-8ebe-3eb0240d3257] pid:30160
[2013-02-20 00:18:41,805: INFO/MainProcess] Got task from broker: workflow.store_results[baef5929-6454-432e-8b84-90b693427f24]
[2013-02-20 00:18:41,806: INFO/MainProcess] Task workflow.provider_licence[3d82f09d-ac13-4666-8ebe-3eb0240d3257] succeeded in 0.00524592399597s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,810: DEBUG/MainProcess] Mediator: Running callback for task: workflow.store_results[baef5929-6454-432e-8b84-90b693427f24]
[2013-02-20 00:18:41,811: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.store_results', u'baef5929-6454-432e-8b84-90b693427f24', [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.store_results', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'baef5929-6454-432e-8b84-90b693427f24'}) kwargs:{})
[2013-02-20 00:18:41,813: DEBUG/MainProcess] Task accepted: workflow.store_results[baef5929-6454-432e-8b84-90b693427f24] pid:30159
[2013-02-20 00:18:41,813: INFO/MainProcess] Task workflow.store_results[baef5929-6454-432e-8b84-90b693427f24] succeeded in 0.00200581550598s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,933: DEBUG/MainProcess] "GET /10.archived/1 HTTP/1.1" 404 2544
[2013-02-20 00:18:41,939: INFO/MainProcess] Got task from broker: workflow.provider_licence[5214205e-b9d1-4e49-a097-2ad58fef2755]
[2013-02-20 00:18:41,940: INFO/MainProcess] Task workflow.detect_provider[b5528098-378d-4af7-85bb-20d08203efa1] succeeded in 0.348295211792s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,976: DEBUG/MainProcess] Mediator: Running callback for task: workflow.provider_licence[5214205e-b9d1-4e49-a097-2ad58fef2755]
[2013-02-20 00:18:41,977: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.provider_licence', u'5214205e-b9d1-4e49-a097-2ad58fef2755', [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.provider_licence', u'callbacks': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'acf07e2e-1c57-49f6-aba9-36ee70a4a8ee'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'5214205e-b9d1-4e49-a097-2ad58fef2755'}) kwargs:{})
[2013-02-20 00:18:41,980: DEBUG/MainProcess] Task accepted: workflow.provider_licence[5214205e-b9d1-4e49-a097-2ad58fef2755] pid:30157
[2013-02-20 00:18:41,983: INFO/MainProcess] Got task from broker: workflow.store_results[acf07e2e-1c57-49f6-aba9-36ee70a4a8ee]
[2013-02-20 00:18:41,984: INFO/MainProcess] Task workflow.provider_licence[5214205e-b9d1-4e49-a097-2ad58fef2755] succeeded in 0.00530600547791s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:41,988: DEBUG/MainProcess] Mediator: Running callback for task: workflow.store_results[acf07e2e-1c57-49f6-aba9-36ee70a4a8ee]
[2013-02-20 00:18:41,989: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.store_results', u'acf07e2e-1c57-49f6-aba9-36ee70a4a8ee', [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.archived/1', u'canonical': u'doi:10.archived/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.store_results', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'acf07e2e-1c57-49f6-aba9-36ee70a4a8ee'}) kwargs:{})
[2013-02-20 00:18:41,991: DEBUG/MainProcess] Task accepted: workflow.store_results[acf07e2e-1c57-49f6-aba9-36ee70a4a8ee] pid:30160
[2013-02-20 00:18:41,992: INFO/MainProcess] Task workflow.store_results[acf07e2e-1c57-49f6-aba9-36ee70a4a8ee] succeeded in 0.00223302841187s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:42,268: DEBUG/MainProcess] "GET /10.stale/1 HTTP/1.1" 404 2532
[2013-02-20 00:18:42,273: INFO/MainProcess] Got task from broker: workflow.provider_licence[ad92d569-929c-49cd-a6ba-18f48a01bdbc]
[2013-02-20 00:18:42,274: INFO/MainProcess] Task workflow.detect_provider[19b6f336-2b2e-4aa1-a7ba-8d62083bc6d8] succeeded in 0.704173088074s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:42,305: DEBUG/MainProcess] Mediator: Running callback for task: workflow.provider_licence[ad92d569-929c-49cd-a6ba-18f48a01bdbc]
[2013-02-20 00:18:42,306: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.provider_licence', u'ad92d569-929c-49cd-a6ba-18f48a01bdbc', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.provider_licence', u'callbacks': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'75a2e33d-b5fd-4209-a979-0b44a5bb47ef'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'ad92d569-929c-49cd-a6ba-18f48a01bdbc'}) kwargs:{})
[2013-02-20 00:18:42,309: DEBUG/MainProcess] Task accepted: workflow.provider_licence[ad92d569-929c-49cd-a6ba-18f48a01bdbc] pid:30159
[2013-02-20 00:18:42,312: INFO/MainProcess] Got task from broker: workflow.store_results[75a2e33d-b5fd-4209-a979-0b44a5bb47ef]
[2013-02-20 00:18:42,313: INFO/MainProcess] Task workflow.provider_licence[ad92d569-929c-49cd-a6ba-18f48a01bdbc] succeeded in 0.00517296791077s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:18:42,316: DEBUG/MainProcess] Mediator: Running callback for task: workflow.store_results[75a2e33d-b5fd-4209-a979-0b44a5bb47ef]
[2013-02-20 00:18:42,317: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.store_results', u'75a2e33d-b5fd-4209-a979-0b44a5bb47ef', [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.stale/1', u'canonical': u'doi:10.stale/1'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.store_results', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'75a2e33d-b5fd-4209-a979-0b44a5bb47ef'}) kwargs:{})
[2013-02-20 00:18:42,319: DEBUG/MainProcess] Task accepted: workflow.store_results[75a2e33d-b5fd-4209-a979-0b44a5bb47ef] pid:30160
[2013-02-20 00:18:42,320: INFO/MainProcess] Task workflow.store_results[75a2e33d-b5fd-4209-a979-0b44a5bb47ef] succeeded in 0.00211691856384s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:23:05,802: INFO/MainProcess] Got task from broker: workflow.detect_provider[2280d68b-23d6-4899-841a-6c941de6d4e3]
[2013-02-20 00:23:05,824: DEBUG/MainProcess] Mediator: Running callback for task: workflow.detect_provider[2280d68b-23d6-4899-841a-6c941de6d4e3]
[2013-02-20 00:23:05,825: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.detect_provider', u'2280d68b-23d6-4899-841a-6c941de6d4e3', [{u'identifier': {u'type': u'doi', u'id': u'10.1371/journal.pone.0035089', u'canonical': u'doi:10.1371/journal.pone.0035089'}, u'queued': True}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.1371/journal.pone.0035089', u'canonical': u'doi:10.1371/journal.pone.0035089'}, u'queued': True}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.detect_provider', u'callbacks': [{u'task': u'workflow.provider_licence', u'args': [], u'options': {u'link': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'ed1ae8e7-ce64-4f0b-b854-c70b1f06d6e5'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'task_id': u'98500ad3-b9c4-48c4-ba28-e880498b7f62'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'2280d68b-23d6-4899-841a-6c941de6d4e3'}) kwargs:{})
[2013-02-20 00:23:05,827: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_range_lookup
[2013-02-20 00:23:05,828: DEBUG/MainProcess] Task accepted: workflow.detect_provider[2280d68b-23d6-4899-841a-6c941de6d4e3] pid:30157
[2013-02-20 00:23:05,828: DEBUG/MainProcess] import error loading provider_range_lookup from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:23:05,828: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_range_lookup at 0x1494cf8>
[2013-02-20 00:23:05,829: DEBUG/MainProcess] applying plugin plugins.doi.provider_range_lookup
[2013-02-20 00:23:05,829: DEBUG/MainProcess] loading plugin from modpath: plugins.doi, and callable: provider_dereference
[2013-02-20 00:23:05,830: DEBUG/MainProcess] import error loading provider_dereference from plugins.doi - path may not be accessible or available in this context
[2013-02-20 00:23:05,830: DEBUG/MainProcess] loaded plugin from plugins.doi: <function provider_dereference at 0x1494d70>
[2013-02-20 00:23:05,831: DEBUG/MainProcess] applying plugin plugins.doi.provider_dereference
[2013-02-20 00:23:05,832: INFO/MainProcess] Starting new HTTP connection (1): dx.doi.org
[2013-02-20 00:23:06,143: DEBUG/MainProcess] "GET /10.1371/journal.pone.0035089 HTTP/1.1" 303 180
[2013-02-20 00:23:06,149: INFO/MainProcess] Got task from broker: workflow.provider_licence[98500ad3-b9c4-48c4-ba28-e880498b7f62]
[2013-02-20 00:23:06,151: INFO/MainProcess] Task workflow.detect_provider[2280d68b-23d6-4899-841a-6c941de6d4e3] succeeded in 0.324010848999s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:23:06,194: DEBUG/MainProcess] Mediator: Running callback for task: workflow.provider_licence[98500ad3-b9c4-48c4-ba28-e880498b7f62]
[2013-02-20 00:23:06,195: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.provider_licence', u'98500ad3-b9c4-48c4-ba28-e880498b7f62', [{u'identifier': {u'type': u'doi', u'id': u'10.1371/journal.pone.0035089', u'canonical': u'doi:10.1371/journal.pone.0035089'}, u'queued': True, u'provider': {u'url': u'http://dx.plos.org/10.1371/journal.pone.0035089'}}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.1371/journal.pone.0035089', u'canonical': u'doi:10.1371/journal.pone.0035089'}, u'queued': True, u'provider': {u'url': u'http://dx.plos.org/10.1371/journal.pone.0035089'}}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.provider_licence', u'callbacks': [{u'task': u'workflow.store_results', u'args': [], u'options': {u'task_id': u'ed1ae8e7-ce64-4f0b-b854-c70b1f06d6e5'}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}], u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'98500ad3-b9c4-48c4-ba28-e880498b7f62'}) kwargs:{})
[2013-02-20 00:23:06,198: DEBUG/MainProcess] Task accepted: workflow.provider_licence[98500ad3-b9c4-48c4-ba28-e880498b7f62] pid:30158
[2013-02-20 00:23:06,201: INFO/MainProcess] Got task from broker: workflow.store_results[ed1ae8e7-ce64-4f0b-b854-c70b1f06d6e5]
[2013-02-20 00:23:06,202: INFO/MainProcess] Task workflow.provider_licence[98500ad3-b9c4-48c4-ba28-e880498b7f62] succeeded in 0.00574111938477s: {u'identifier': {u'type': u'doi', u'id':...
[2013-02-20 00:23:06,203: DEBUG/MainProcess] Mediator: Running callback for task: workflow.store_results[ed1ae8e7-ce64-4f0b-b854-c70b1f06d6e5]
[2013-02-20 00:23:06,204: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x109a5f0> (args:(u'workflow.store_results', u'ed1ae8e7-ce64-4f0b-b854-c70b1f06d6e5', [{u'identifier': {u'type': u'doi', u'id': u'10.1371/journal.pone.0035089', u'canonical': u'doi:10.1371/journal.pone.0035089'}, u'queued': True, u'provider': {u'url': u'http://dx.plos.org/10.1371/journal.pone.0035089'}}], {}, {u'utc': True, 'is_eager': False, u'chord': None, 'group': None, u'args': [{u'identifier': {u'type': u'doi', u'id': u'10.1371/journal.pone.0035089', u'canonical': u'doi:10.1371/journal.pone.0035089'}, u'queued': True, u'provider': {u'url': u'http://dx.plos.org/10.1371/journal.pone.0035089'}}], u'retries': 0, 'delivery_info': {'priority': 0, 'routing_key': 'celery', 'exchange': 'celery'}, u'expires': None, u'task': u'workflow.store_results', u'callbacks': None, u'errbacks': None, 'hostname': 'holly', u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'ed1ae8e7-ce64-4f0b-b854-c70b1f06d6e5'}) kwargs:{})
[2013-02-20 00:23:06,206: DEBUG/MainProcess] Task accepted: workflow.store_results[ed1ae8e7-ce64-4f0b-b854-c70b1f06d6e5] pid:30159
[2013-02-20 00:23:06,206: INFO/MainProcess] Task workflow.store_results[ed1ae8e7-ce64-4f0b-b854-c70b1f06d6e5] succeeded in 0.00186491012573s: {u'identifier': {u'type': u'doi', u'id':...
